[package]
name = "libsynfig-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "synfig"
path = "src/lib.rs"

[dependencies]
lazy_static = "1.4.0"
log = "0.4.17"
env_logger = "0.9.1"